Arrays


In [1]:
%pip install numpy


import numpy as np

marks = np.array([88, 75, 66, 99])

print("Original Marks:", marks)
print("Marks + 5:", marks + 5)
print("Marks - 5:", marks - 5)
print("Marks / 2:", marks / 2)

marks = np.array([88, 75, 66, 99])

print("Original Marks:", marks)
print("Marks + 5:", marks + 5)
print("Marks - 5:", marks - 5)
print("Marks / 2:", marks / 2)


Note: you may need to restart the kernel to use updated packages.
Original Marks: [88 75 66 99]
Marks + 5: [ 93  80  71 104]
Marks - 5: [83 70 61 94]
Marks / 2: [44.  37.5 33.  49.5]
Original Marks: [88 75 66 99]
Marks + 5: [ 93  80  71 104]
Marks - 5: [83 70 61 94]
Marks / 2: [44.  37.5 33.  49.5]


Indexing


In [2]:
print(marks[-2])
print(marks[-3])
print(marks[-1])
print(marks[-4])

66
75
99
88


In [3]:
print(marks[3])
print(marks[2])
print(marks[1])

99
66
75


Traversing


In [4]:
for i in range(4):
    print(marks[i])

88
75
66
99


Slicing

In [5]:
marks[:2] # Academic team wants first 2 marks
marks[1:4] 

array([75, 66, 99])

In [6]:
import numpy as np

marks = np.array([
    [85, 78, 90],
    [92, 85, 98],
    [76, 82, 80]
])

    #Rows -> Students
    #Columns -> Subjects


2D slicing & indexing


In [7]:
print(marks)

[[85 78 90]
 [92 85 98]
 [76 82 80]]


In [8]:
marks[0,0]

np.int64(85)

In [9]:
marks[0:1][0:2] # array[row,column]---> indexing

array([[85, 78, 90]])

In [10]:
marks[0:2] #array [start:stop-1] -----> slicing

array([[85, 78, 90],
       [92, 85, 98]])

In [11]:
marks[1:0] 
print(marks)

[[85 78 90]
 [92 85 98]
 [76 82 80]]


In [12]:
print(marks[1:,0])
print(marks[1:][0])


[92 76]
[92 85 98]


In [13]:
# marks[1:]
#[[92 85 98
#76 82 80]]


In [14]:
print (marks[1:,0])



[92 76]


Combined Array

In [15]:
b1 = np.array([
    [56, 78, 89],
    [34, 45, 67]
])
b2 = np.array([
    [65, 76, 98],
    [89, 98, 78]
])
comb = np.concatenate((b1, b2), axis=1)
comb

#axis
# array([[56, 78, 89, 65, 76, 98],
#        [34, 45, 67, 89, 98, 78]])
print(comb)
print("------------------")
comb0=np.concatenate((b1,b2),axis = 0)
comb0

[[56 78 89 65 76 98]
 [34 45 67 89 98 78]]
------------------


array([[56, 78, 89],
       [34, 45, 67],
       [65, 76, 98],
       [89, 98, 78]])

A combined dataset contains six students. The academic team wants to divide the data into two groups for separate processing.  
Split - Always in an equal division
Join - Combine 




In [16]:
for arr in np.split(comb, 3, axis=1):
    print(arr)


[[56 78]
 [34 45]]
[[89 65]
 [67 89]]
[[76 98]
 [98 78]]


In [17]:
# Find the row and column indices where the mark is 78
print(np.where(marks==78))
print(marks)



(array([0]), array([1]))
[[85 78 90]
 [92 85 98]
 [76 82 80]]


In [18]:
# Find where the mark is greater than 78

marks = np.array([
    [85, 78, 90],
    [92, 85, 98],
    [76, 82, 80]
])
print(np.where(marks>80))
print(marks)



(array([0, 0, 1, 1, 1, 2]), array([0, 2, 0, 1, 2, 1]))
[[85 78 90]
 [92 85 98]
 [76 82 80]]


Examples

In [19]:
# Find where the mark is greater than 80 
import numpy as np

# Define the 2D array
marks = np.array([
    [85, 78, 90],
    [92, 85, 98],
    [76, 82, 80]
])

# Condition: marks greater than 80
greater_than_80 = marks > 80

# Extract values
result = marks[greater_than_80]
# Find marks greater than or equal to 80
rows, columns = np.where(marks >= 80)

print("Indices:")
print("Rows:", rows)
print("Columns:", columns)

print("Original Marks:\n", marks)
print("Marks greater than or equal to 80:", marks[marks >= 80])

print("Sorted Marks:\n", np.sort(marks))
print((rows, columns))

print("Original Marks:\n", marks)
print("Marks greater than 80:", result)  # Gives exact values
np.sort(marks)[::-1]  # Row wise sort 
np.sort(marks,axis=1) # Column wise sort 




Indices:
Rows: [0 0 1 1 1 2 2]
Columns: [0 2 0 1 2 1 2]
Original Marks:
 [[85 78 90]
 [92 85 98]
 [76 82 80]]
Marks greater than or equal to 80: [85 90 92 85 98 82 80]
Sorted Marks:
 [[78 85 90]
 [85 92 98]
 [76 80 82]]
(array([0, 0, 1, 1, 1, 2, 2]), array([0, 2, 0, 1, 2, 1, 2]))
Original Marks:
 [[85 78 90]
 [92 85 98]
 [76 82 80]]
Marks greater than 80: [85 90 92 85 98 82]


array([[78, 85, 90],
       [85, 92, 98],
       [76, 80, 82]])

In [20]:
np.sort(marks , axis=1)

array([[78, 85, 90],
       [85, 92, 98],
       [76, 80, 82]])